registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/certificate.crt
    REGISTRY_HTTP_TLS_KEY: /certs/private.key
  volumes:
    - ${DOCKER_REG_FILES}/data:/var/lib/registry
    - ${DOCKER_REG_FILES}/certs:/certs
    - ${DOCKER_REG_FILES}/auth:/auth
